### ISSUE TITLE
Hi~Is there any difference between  Inception and Inception Transpose？

### ISSUE THREAD

**Issue by mz2sj** [TheMrGhostman/InceptionTime-Pytorch#1]
Thank you for your code.I am interested in TSC.Your code gives an example of univariate and each time series  has equal length.I have a multivariable time sereis  and they are unequal length.How can I solve this  problem,just padding like NLP?
Thank you.

**Comment by TheMrGhostman** [comment]
hi, my version of Inception Transposed is like mirror-inverted Inception. I tried to use it for my convolutional variational auto-encoder (easier parameter search). 

inceprion(params) -> latent space -> inception transposed(params)

It works but there are better architectures for decoder. 

My code works the same for univariate and multivariate time series (difference is just number of channels for first bottleneck).  Unequal length is problem. Ofc padding is the easiest solution. However as usual, the data matters the most. If lengths of  signals are different but fixed, you can just modify first inception layer or do some preprocessing (upsampling resp. downsampling).

**Comment by mz2sj** [comment]
Thank you！
