### ISSUE TITLE
About the UCR Time Series Classification Archive

### ISSUE THREAD

**Issue by iamstarlee** [TheMrGhostman/InceptionTime-Pytorch#5]
Hi, do you know the password of this archive? I have looked through the [PowerPoint](https://www.cs.ucr.edu/%7Eeamonn/time_series_data/), but have no idea what 'So, the password is the three redacted words from this sentence  “Every item that we *******##@@@@@@@ belongs to exactly one of our well-defined classes”, after you remove the two spaces.' mean. 
> *******##@@@@@@@

is not correct.
Your help will be much appreciated!

**Comment by TheMrGhostman** [comment]
I did not use that archiv so i do not know.

**Comment by iamstarlee** [comment]
I got it. I missed the following paragraph, which said I need to download a paper from which the three redacted words are `attempt to classify`.
![image](https://github.com/user-attachments/assets/f9abad38-88b6-4707-9fca-12b34d974f06)
![image](https://github.com/user-attachments/assets/d18b40e6-3248-44aa-a88a-eb181e3f3271)
